using ReqLens.Domain;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;

namespace ReqLens.Ocr;

/// <summary>
/// Reads the text layer straight out of a born-digital PDF, with no OCR at all.
/// </summary>
/// <remarks>
/// NOT a substitute for OCR, and it must not be described as one. It works here because the
/// synthetic requisitions are generated by QuestPDF and therefore carry a real text layer. A
/// requisition that arrived the way real ones do - faxed, scanned, photographed - is an image,
/// and this class would return nothing at all for it.
///
/// It earns its place for two reasons. It makes the eval harness free and offline, so the golden
/// set can be re-run on every model change without paying per page. And it keeps the pipeline
/// demonstrable end to end while this account's Textract subscription is unavailable, which is
/// not a thing that can be fixed in code.
///
/// Confidence is reported as null throughout, because there is no measurement being made. A text
/// layer is read exactly or not at all, so there is no score to give. Null rather than 100
/// because a stand-in number - however obviously round - flows into the same telemetry field
/// that carries a real Textract score and quietly corrupts it.
/// </remarks>
public sealed class PdfTextLayerOcr : IOcrProvider
{
    public string Name => OcrProviders.PdfTextLayerName;

    public Task<OcrDocument> ReadAsync(
        byte[] document,
        string sourceObjectKey,
        string tenantSlug,
        Guid orderId,
        CancellationToken cancellationToken = default)
    {
        using var pdf = PdfDocument.Open(document);

        var lines = new List<OcrLine>();

        foreach (var page in pdf.GetPages())
        {
            foreach (var line in LinesOf(page))
                lines.Add(line);
        }

        return Task.FromResult(new OcrDocument
        {
            SourceObjectKey = sourceObjectKey,
            TenantSlug = tenantSlug,
            OrderId = orderId,
            PageCount = pdf.NumberOfPages,
            Lines = lines,

            // Form key/value pairing is a Textract feature. There is nothing to derive it from
            // here, and inventing pairs by guessing at labels would be the extraction step doing
            // itself badly one layer too early.
            KeyValues = []
        });
    }

    /// <summary>
    /// Groups words into lines by their vertical position on the page.
    /// </summary>
    /// <remarks>
    /// PdfPig reports words in content-stream order, which is the order the generator emitted
    /// them and not necessarily reading order. Grouping by baseline and then sorting left to
    /// right reconstructs lines reliably for these layouts. The tolerance is in PDF points; two
    /// words on the same visual line share a baseline to well within it.
    /// </remarks>
    private static IEnumerable<OcrLine> LinesOf(Page page)
    {
        const double BaselineTolerance = 2.5;

        var words = page.GetWords()
            .Where(w => !string.IsNullOrWhiteSpace(w.Text))
            .ToList();

        var rows = new List<List<Word>>();

        foreach (var word in words.OrderByDescending(w => w.BoundingBox.Bottom).ThenBy(w => w.BoundingBox.Left))
        {
            var row = rows.FirstOrDefault(r =>
                Math.Abs(r[0].BoundingBox.Bottom - word.BoundingBox.Bottom) <= BaselineTolerance);

            if (row is null) rows.Add([word]);
            else row.Add(word);
        }

        foreach (var row in rows)
        {
            var ordered = row.OrderBy(w => w.BoundingBox.Left).ToList();
            var text = string.Join(' ', ordered.Select(w => w.Text)).Trim();

            if (text.Length == 0) continue;

            var left = ordered[0].BoundingBox.Left;
            var bottom = ordered[0].BoundingBox.Bottom;

            // Normalised to the 0..1 origin-at-top-left coordinates Textract reports, so both
            // providers describe a position the same way.
            yield return new OcrLine(
                text,
                Confidence: null,
                Top: (float)(1 - bottom / page.Height),
                Left: (float)(left / page.Width),
                Page: page.Number);
        }
    }
}
