// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReqLens.Data;

#nullable disable

namespace ReqLens.Data.Migrations
{
    [DbContext(typeof(ReqLensDbContext))]
    [Migration("20260831202008_AddExtractionCallsAndReviewReasons")]
    partial class AddExtractionCallsAndReviewReasons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReqLens.Domain.ExtractedField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<bool?>("Grounded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<string>("SourceText")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("text");

                    b.Property<int>("ValidationState")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("ReqLens.Domain.ExtractionCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("GuardrailIntervened")
                        .HasColumnType("boolean");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<double?>("MinFieldConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("SchemaValid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "At");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("ExtractionCalls");
                });

            modelBuilder.Entity("ReqLens.Domain.LabOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionFailure")
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .HasColumnType("text");

                    b.Property<double?>("OverallConfidence")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("ReviewReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SourceObjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ReqLens.Domain.ReviewAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueAfter")
                        .HasColumnType("text");

                    b.Property<string>("ValueBefore")
                        .HasColumnType("text");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "At");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ReqLens.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ReqLens.Domain.TestCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecimenType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("TestCatalog");
                });

            modelBuilder.Entity("ReqLens.Domain.ExtractedField", b =>
                {
                    b.HasOne("ReqLens.Domain.LabOrder", null)
                        .WithMany("Fields")
                        .HasForeignKey("TenantId", "OrderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReqLens.Domain.ExtractionCall", b =>
                {
                    b.HasOne("ReqLens.Domain.LabOrder", null)
                        .WithMany("Calls")
                        .HasForeignKey("TenantId", "OrderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReqLens.Domain.LabOrder", b =>
                {
                    b.HasOne("ReqLens.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReqLens.Domain.ReviewAction", b =>
                {
                    b.HasOne("ReqLens.Domain.LabOrder", null)
                        .WithMany("Reviews")
                        .HasForeignKey("TenantId", "OrderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReqLens.Domain.TestCatalogEntry", b =>
                {
                    b.HasOne("ReqLens.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReqLens.Domain.LabOrder", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Fields");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
